### ISSUE TITLE
“undefined reference to” Error during `catkin_make`

### ISSUE THREAD

**Issue by thedomdom** [lovepark/royale-ros#2]
Dear love park team,

I am having problems installing this package. I followed every step in "Installing the pmd Royale SDK" and "Installing the ROS node" but when running the command `catkin_make` it leads to the following error:

	[ 33%] Built target dump
	Linking CXX executable /home/dominik/catkin_ws/royale/devel/lib/royale_ros/lscam
	/opt/libroyale-3.12.0.44-LINUX-x86-64Bit/bin/libroyale.so: undefined reference to `VTT for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
	/opt/libroyale-3.12.0.44-LINUX-x86-64Bit/bin/libroyale.so: undefined reference to `std::logic_error::logic_error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'
	/opt/libroyale-3.12.0.44-LINUX-x86-64Bit/bin/libroyale.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'
	/opt/libroyale-3.12.0.44-LINUX-x86-64Bit/bin/libroyale.so: undefined reference to `std::logic_error::logic_error(std::logic_error const&)@GLIBCXX_3.4.21'
	/opt/libroyale-3.12.0.44-LINUX-x86-64Bit/bin/libroyale.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::reserve(unsigned long)@GLIBCXX_3.4.21'
	/opt/libroyale-3.12.0.44-LINUX-x86-64Bit/bin/libroyale.so: undefined reference to `std::length_error::length_error(char const*)@GLIBCXX_3.4.21'
	/opt/libroyale-3.12.0.44-LINUX-x86-64Bit/bin/libroyale.so: undefined reference to `std::out_of_range::out_of_range(char const*)@GLIBCXX_3.4.21'
	/opt/libroyale-3.12.0.44-LINUX-x86-64Bit/bin/libroyale.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::resize(unsigned long, char)@GLIBCXX_3.4.21'
	/opt/libroyale-3.12.0.44-LINUX-x86-64Bit/bin/libroyale.so: undefined reference to `vtable for std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
	/opt/libroyale-3.12.0.44-LINUX-x86-64Bit/bin/libspectre3.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_erase(unsigned long, unsigned long)@GLIBCXX_3.4.21'
	/opt/libroyale-3.12.0.44-LINUX-x86-64Bit/bin/libroyale.so: undefined reference to `std::logic_error::logic_error(char const*)@GLIBCXX_3.4.21'
	/opt/libroyale-3.12.0.44-LINUX-x86-64Bit/bin/libroyale.so: undefined reference to `std::invalid_argument::invalid_argument(char const*)@GLIBCXX_3.4.21'
	/opt/libroyale-3.12.0.44-LINUX-x86-64Bit/bin/libroyale.so: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)@GLIBCXX_3.4.20'
	/opt/libroyale-3.12.0.44-LINUX-x86-64Bit/bin/libroyale.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long)@GLIBCXX_3.4.21'
	/opt/libroyale-3.12.0.44-LINUX-x86-64Bit/bin/libroyale.so: undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_stringstream()@GLIBCXX_3.4.21'
	/opt/libroyale-3.12.0.44-LINUX-x86-64Bit/bin/libroyale.so: undefined reference to `std::runtime_error::runtime_error(char const*)@GLIBCXX_3.4.21'
	/opt/libroyale-3.12.0.44-LINUX-x86-64Bit/bin/libspectre3.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct(unsigned long, char)@GLIBCXX_3.4.21'
	/opt/libroyale-3.12.0.44-LINUX-x86-64Bit/bin/libroyale.so: undefined reference to `std::logic_error::logic_error(std::logic_error const&)@GLIBCXX_3.4.21'
	/opt/libroyale-3.12.0.44-LINUX-x86-64Bit/bin/libspectre3.so: undefined reference to `__cxa_throw_bad_array_new_length@CXXABI_1.3.8'
	/opt/libroyale-3.12.0.44-LINUX-x86-64Bit/bin/libroyale.so: undefined reference to `std::runtime_error::runtime_error(std::runtime_error const&)@GLIBCXX_3.4.21'
	/opt/libroyale-3.12.0.44-LINUX-x86-64Bit/bin/libroyale.so: undefined reference to `vtable for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
	/opt/libroyale-3.12.0.44-LINUX-x86-64Bit/bin/libroyale.so: undefined reference to `vtable for std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
	/opt/libroyale-3.12.0.44-LINUX-x86-64Bit/bin/libroyale.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)@GLIBCXX_3.4.21'
	/opt/libroyale-3.12.0.44-LINUX-x86-64Bit/bin/libroyale.so: undefined reference to `std::basic_istream<char, std::char_traits<char> >& std::getline<char, std::char_traits<char>, std::allocator<char> >(std::basic_istream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, char)@GLIBCXX_3.4.21'
	/opt/libroyale-3.12.0.44-LINUX-x86-64Bit/bin/libroyale.so: undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::_M_sync(char*, unsigned long, unsigned long)@GLIBCXX_3.4.21'
	/opt/libroyale-3.12.0.44-LINUX-x86-64Bit/bin/libroyale.so: undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream(std::_Ios_Openmode)@GLIBCXX_3.4.21'
	/opt/libroyale-3.12.0.44-LINUX-x86-64Bit/bin/libroyale.so: undefined reference to `std::basic_istream<char, std::char_traits<char> >& std::operator>><char, std::char_traits<char>, std::allocator<char> >(std::basic_istream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)@GLIBCXX_3.4.21'
	/opt/libroyale-3.12.0.44-LINUX-x86-64Bit/bin/libroyale.so: undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_ostringstream()@GLIBCXX_3.4.21'
	/opt/libroyale-3.12.0.44-LINUX-x86-64Bit/bin/libroyale.so: undefined reference to `vtable for std::__cxx11::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
	/opt/libroyale-3.12.0.44-LINUX-x86-64Bit/bin/libroyale.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(char const*) const@GLIBCXX_3.4.21'
	/opt/libroyale-3.12.0.44-LINUX-x86-64Bit/bin/libroyale.so: undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const@GLIBCXX_3.4.21'
	/opt/libroyale-3.12.0.44-LINUX-x86-64Bit/bin/libroyale.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::swap(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)@GLIBCXX_3.4.21'
	/opt/libroyale-3.12.0.44-LINUX-x86-64Bit/bin/libroyale.so: undefined reference to `std::thread::_M_start_thread(std::shared_ptr<std::thread::_Impl_base>, void (*)())@GLIBCXX_3.4.21'
	/opt/libroyale-3.12.0.44-LINUX-x86-64Bit/bin/libroyale.so: undefined reference to `VTT for std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
	/opt/libroyale-3.12.0.44-LINUX-x86-64Bit/bin/libroyale.so: undefined reference to `std::__cxx11::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_istringstream()@GLIBCXX_3.4.21'
	/opt/libroyale-3.12.0.44-LINUX-x86-64Bit/bin/libroyale.so: undefined reference to `VTT for std::__cxx11::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
	/opt/libroyale-3.12.0.44-LINUX-x86-64Bit/bin/libroyale.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()@GLIBCXX_3.4.21'
	/opt/libroyale-3.12.0.44-LINUX-x86-64Bit/bin/libroyale.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long)@GLIBCXX_3.4.21'
	/opt/libroyale-3.12.0.44-LINUX-x86-64Bit/bin/libspectre3.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(unsigned long, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const@GLIBCXX_3.4.21'
	/opt/libroyale-3.12.0.44-LINUX-x86-64Bit/bin/libroyale.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'
	/opt/libroyale-3.12.0.44-LINUX-x86-64Bit/bin/libroyale.so: undefined reference to `std::runtime_error::runtime_error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'
	collect2: error: ld returned 1 exit status
	make[2]: *** [/home/dominik/catkin_ws/royale/devel/lib/royale_ros/lscam] Error 1
	make[1]: *** [royale/CMakeFiles/lscam.dir/all] Error 2
	make: *** [all] Error 2
	Invoking "make -j1 -l1" failed

How can I fix this error? Is it an error caused by royale or do I have the wrong version of GLIBCXX_3.4.21 installed?

`apt-show-versions libstdc++6` shows the following:
`libstdc++6:amd64/trusty 4.8.4-2ubuntu1~14.04.3 upgradeable to 7.2.0-1ubuntu1~14.04`

EDIT: I upgraded it and it now shows:
`libstdc++6:amd64/trusty 7.2.0-1ubuntu1~14.04 uptodate`

`strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX` now contains `GLIBCXX_3.4.21`:

	GLIBCXX_3.4
	GLIBCXX_3.4.1
	GLIBCXX_3.4.2
	[...]
	GLIBCXX_3.4.20
	GLIBCXX_3.4.21
	GLIBCXX_3.4.22
	GLIBCXX_3.4.23
	GLIBCXX_3.4.24
	GLIBCXX_DEBUG_MESSAGE_LENGTH

I am using ROS Indigo on Ubuntu 14.04 .

I have been researching the whole day and can't find a solution. I think I don't have enough knowledge about C++, `make` and ROS yet to find the solution myself. Any help would be very appreciated!

**Comment by graugans** [comment]
It looks like the Royale version is not matching your Distribution. I have no Royale available to check this.

**Comment by thedomdom** [comment]
I installed royale according to your guide [Installing the Royale SDK](https://github.com/lovepark/royale-ros/blob/master/doc/royale_install.md).

`uname -a` outputs the following:
`Linux ubuntu 4.4.0-31-generic #50~14.04.1-Ubuntu SMP Wed Jul 13 01:07:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`  --> So I have 64 Ubuntu 14.04

The name of the automatically generated debian package is `royale-sdk_3.12.0-44_amd64.deb`. --> So this should match.

I think it is not an error with royale but with something in `makelists.txt`. Linking to `@GLIBCXX_3.4.21` does not work correctly...

**Comment by tpanzarella** [comment]
Per [the link you mentioned](https://github.com/lovepark/royale-ros/blob/master/doc/royale_install.md), did you install the "full" SDK? Can you run the `royaleviewer.sh` script and see output similar to what is shown? It would be good to isolate Royale from ROS to see where the issue is.

If the above does not work, I would then try to re-install Royale by not using the [debianize-royale.py](https://github.com/lovepark/royale-ros/blob/master/utils/debianize-royale.py) script so that we can see if the bug is in that packaging or in the royale packaging itself.

**Comment by tpanzarella** [comment]
Per one of the Royale developers:

> with Royale 3.12, we switched to Ubuntu 16.04 LTS as a system requirement. It's plausible that it won't work with 14.04. With 3.11, we started a new Royale-LTS version, which remains on Ubuntu 14.04. It might be worth a shot to try this.

**Comment by thedomdom** [comment]
No, I did not install the full SDK, because I want to use it with ROS. And the guide says: "... it will install the full Royale SDK, including the GUI, example programs, documentation, etc. For ROS users, this is not recommended."

Ok, I will try that. I recognized that in the most recent Royale SDK, there is a `sampleROS` folder including a ROS node that publishes 4 topics:

- `camera_info` : provide camera information
- `point_cloud` : PointCloud2 of ROS with 3 channels (x, y and z of Royale DepthData)
- `depth_image` : TYPE_32FC1 image. It also supports point cloud which is called "DepthCloud" in this topic.
- `gray_image`  : MONO16 image. The brightness of gray image can be adjusted by `gray_divisor` in dynamic reconfigure.

I will also try that out and use this if it works.

**Comment by tpanzarella** [comment]
> No, I did not install the full SDK, because I want to use it with ROS. And the guide says: "... it will install the full Royale SDK, including the GUI, example programs, documentation, etc. For ROS users, this is not recommended."

Right. Just for troubleshooting purposes, it would be useful. The reason for the *warning* to ROS users there is that IIRC, royale bundles its own Qt in the same `lib` directory as everything else. This then conflicts with the Qt version provided by ROS which then makes all the `rqt_XXX` ROS tools useless.

**Comment by thedomdom** [comment]
Ok, thank you so much for the hint, that it is not supposed to work with Ubuntu 14.04!
Luckily, I still have the old royale version 3.11 as I don't know where I could download it (pmd only lets it's users download the most recent version... ).
I will also try out that and I think this should work!

**Comment by thedomdom** [comment]
So I tried to use this wrapper with the royale version 3.11 but unfortunately it did not work.
The error was  `ld: cannot find -lroyale` even if I installed royale with `dpkg`.
I am now just using the `sampleROS` driver from the 3.11 royale and it works fine (I an see the point cloud in rviz).

**Comment by tpanzarella** [comment]
I will try to take a look at this this week and get some clarity on it for you.
